---
title: "margin and win% for HT and FT"
output: html_document
---

GOAL:
Extract Half Time and Full Time scores

```{r}
#store the links to all pages required

home.england.2015.to.2018.page <- "http://stats.espnscrum.com/statsguru/rugby/stats/index.html?class=1;home_or_away=1;spanmax1=31+Dec+2018;spanmin1=1+Jan+2015;spanval1=span;team=1;template=results;trophy=2;type=team;view=results"

away.england.2015.to.2018.page <- "http://stats.espnscrum.com/statsguru/rugby/stats/index.html?class=1;home_or_away=2;spanmax1=31+Dec+2018;spanmin1=1+Jan+2015;spanval1=span;team=1;template=results;trophy=2;type=team;view=results"

home.france.2015.to.2018.page <- "http://stats.espnscrum.com/statsguru/rugby/stats/index.html?class=1;home_or_away=1;spanmax1=31+Dec+2018;spanmin1=1+Jan+2015;spanval1=span;team=9;template=results;trophy=2;type=team;view=results"
  
away.france.2015.to.2018.page <- "http://stats.espnscrum.com/statsguru/rugby/stats/index.html?class=1;home_or_away=2;spanmax1=31+Dec+2018;spanmin1=1+Jan+2015;spanval1=span;team=9;template=results;trophy=2;type=team;view=results"

home.ireland.2015.to.2018.page <- "http://stats.espnscrum.com/statsguru/rugby/stats/index.html?class=1;home_or_away=1;spanmax1=31+Dec+2018;spanmin1=1+Jan+2015;spanval1=span;team=3;template=results;trophy=2;type=team;view=results"

away.ireland.2015.to.2018.page <- "http://stats.espnscrum.com/statsguru/rugby/stats/index.html?class=1;home_or_away=2;spanmax1=31+Dec+2018;spanmin1=1+Jan+2015;spanval1=span;team=3;template=results;trophy=2;type=team;view=results"

home.italy.2015.to.2018.page <- "http://stats.espnscrum.com/statsguru/rugby/stats/index.html?class=1;home_or_away=1;spanmax1=31+Dec+2018;spanmin1=1+Jan+2015;spanval1=span;team=20;template=results;trophy=2;type=team;view=results"

away.italy.2015.to.2018.page <- "http://stats.espnscrum.com/statsguru/rugby/stats/index.html?class=1;home_or_away=2;spanmax1=31+Dec+2018;spanmin1=1+Jan+2015;spanval1=span;team=20;template=results;trophy=2;type=team;view=results"

home.scotland.2015.to.2018.page <- "http://stats.espnscrum.com/statsguru/rugby/stats/index.html?class=1;home_or_away=1;spanmax1=31+Dec+2018;spanmin1=1+Jan+2015;spanval1=span;team=2;template=results;trophy=2;type=team;view=results"

away.scotland.2015.to.2018.page <- "http://stats.espnscrum.com/statsguru/rugby/stats/index.html?class=1;home_or_away=2;spanmax1=31+Dec+2018;spanmin1=1+Jan+2015;spanval1=span;team=2;template=results;trophy=2;type=team;view=results"

home.wales.2015.to.2018.page <- "http://stats.espnscrum.com/statsguru/rugby/stats/index.html?class=1;home_or_away=1;spanmax1=31+Dec+2018;spanmin1=1+Jan+2015;spanval1=span;team=4;template=results;trophy=2;type=team;view=results"

away.wales.2015.to.2018.page <- "http://stats.espnscrum.com/statsguru/rugby/stats/index.html?class=1;home_or_away=2;spanmax1=31+Dec+2018;spanmin1=1+Jan+2015;spanval1=span;team=4;template=results;trophy=2;type=team;view=results"
```

```{r}
#extract the 40 cells of data
library(rvest)

home.england.html.vector <- readLines(home.england.2015.to.2018.page)

home.england.html.lines <- regmatches(home.england.html.vector, regexpr("<td>[[:digit:]]{1,3}</td>", home.england.html.vector))

home.england <- substr(home.england.html.lines, 5, nchar(home.england.html.lines)-5)

home.england.matrix <- matrix(as.integer(home.england), ncol = 4, byrow = TRUE)
home.england.matrix
```

These are the 40 cells we are interested in.

The pattern is:

FTFor, FTAgainst, HTFor, HTAgainst

```{r}
#The logic above as a function

extract.score.cells.from.webpage <- function(link){
  html.vector <- readLines(link)
  html.lines <- regmatches(html.vector, regexpr("<td>[[:digit:]]{1,3}</td>", html.vector))
  html.lines.trimmed <- substr(html.lines, 5, nchar(html.lines)-5)
  matrix <- matrix(as.integer(html.lines.trimmed), ncol = 4, byrow = TRUE)
  return(matrix)
}

extract.score.cells.from.webpage(home.england.2015.to.2018.page)
```

```{r}
write.csv(home.england.matrix, "./6nationsHomeAdvantages/home.england.matrix.csv")

#Run the function for the other 11 links
#Then save it as a csv to be safe

away.england.matrix <- extract.score.cells.from.webpage(away.england.2015.to.2018.page)
write.csv(away.england.matrix, "./6nationsHomeAdvantages/away.england.matrix.csv")

away.france.matrix <- extract.score.cells.from.webpage(away.france.2015.to.2018.page)
write.csv(away.france.matrix, "./6nationsHomeAdvantages/away.france.matrix.csv")

away.ireland.matrix <- extract.score.cells.from.webpage(away.ireland.2015.to.2018.page)
write.csv(away.ireland.matrix, "./6nationsHomeAdvantages/away.ireland.matrix.csv")

away.italy.matrix <- extract.score.cells.from.webpage(away.italy.2015.to.2018.page)
write.csv(away.italy.matrix, "./6nationsHomeAdvantages/away.italy.matrix.csv")

away.scotland.matrix <- extract.score.cells.from.webpage(away.scotland.2015.to.2018.page)
write.csv(away.scotland.matrix, "./6nationsHomeAdvantages/away.scotland.matrix.csv")

home.france.matrix <- extract.score.cells.from.webpage(home.france.2015.to.2018.page)
write.csv(home.france.matrix, "./6nationsHomeAdvantages/home.france.matrix.csv")

home.italy.matrix <- extract.score.cells.from.webpage(home.italy.2015.to.2018.page)
write.csv(home.italy.matrix, "./6nationsHomeAdvantages/home.italy.matrix.csv")

home.scotland.matrix <- extract.score.cells.from.webpage(home.scotland.2015.to.2018.page)
write.csv(home.scotland.matrix, "./6nationsHomeAdvantages/home.scotland.matrix.csv")

home.wales.matrix <- extract.score.cells.from.webpage(home.wales.2015.to.2018.page)
write.csv(home.wales.matrix, "./6nationsHomeAdvantages/home.wales.matrix.csv")
```

Remove the 0 after 16 in the Wales away and Ireland home data because that 0 represents the final scoe's margin rather than a cell we are interested in.

```{r}
extract.score.cells.from.webpage.special <- function(link){
  html.vector <- readLines(link)
  html.lines <- regmatches(html.vector, regexpr("<td>[[:digit:]]{1,3}</td>", html.vector))
  html.lines.trimmed <- substr(html.lines, 5, nchar(html.lines)-5)
  matrix <- matrix(as.integer(html.lines.trimmed)[-c(11)], ncol = 4, byrow = TRUE) #HARD CODING
  return(matrix)
}

extract.score.cells.from.webpage.special2 <- function(link){
  html.vector <- readLines(link)
  html.lines <- regmatches(html.vector, regexpr("<td>[[:digit:]]{1,3}</td>", html.vector))
  html.lines.trimmed <- substr(html.lines, 5, nchar(html.lines)-5)
  matrix <- matrix(as.integer(html.lines.trimmed)[-c(15)], ncol = 4, byrow = TRUE) #HARD CODING
  return(matrix)
}

away.wales.matrix <- extract.score.cells.from.webpage.special2(away.wales.2015.to.2018.page)
away.wales.matrix
write.csv(away.wales.matrix, "./6nationsHomeAdvantages/away.wales.matrix.csv")

home.ireland.matrix <- extract.score.cells.from.webpage.special(home.ireland.2015.to.2018.page)
home.ireland.matrix
write.csv(home.ireland.matrix, "./6nationsHomeAdvantages/home.ireland.matrix.csv")
```